name: 'OpenVPN-Connect'
description: 'connect to OpenVPN server'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  config_file:
    description: 'Location of OpenVPN client config file'
    required: true
  host:
    description: 'Host'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  port:
    description: 'Port'
    required: false
    default: '1194'
  protocol:
    description: 'Protocol'
    required: false
    default: 'udp4'
  tls_auth_key:
    description: 'Pre-shared group key for TLS Auth'
    required: false
  tls_crypt_key:
    description: 'Pre-shared group key for TLS Crypt'
    required: false
  tls_crypt_v2_key:
    description: 'Per-client key for TLS Crypt V2'
    required: false
  client_key:
    description: "Local peer's private key"
    required: false
  client_pass:
    description: "Local peer's private key's passphrase"
    required: false
  ca:
    description: 'CA that signed the private key'
    required: false
  cert:
    description: "CA's signing certificate"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
