name: "OpenVPN-Connect"
description: "connect to OpenVPN server"
branding:
  icon: "lock"
  color: "green"
inputs:
  config_file:
    description: "Location of OpenVPN client config file"
    required: true
  username:
    description: "Username"
    required: false
  password:
    description: "Password"
    required: false
  tls_auth_key:
    description: "TLS-auth pre-shared group key"
    required: false
  tls_crypt_key:
    description: "TLS-crypt pre-shared group key"
    required: false
  tls_crypt_v2_key:
    description: "Pre-shared secret for tls-crypt-v2"
    required: false
  client_key:
    description: "Local peer's private key"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
